SELECT TOP (1000) [id]
      ,[order_id]
      ,[date]
      ,[status]
      ,[fulfilment]
      ,[sales]
      ,[ship_service_level]
      ,[style]
      ,[sku]
      ,[category]
      ,[size]
      ,[asin]
      ,[courier_status]
      ,[quantity]
      ,[currency]
      ,[amount]
      ,[ship_city]
      ,[ship_state]
      ,[ship_postcode]
      ,[ship_country]
      ,[promotion_ids]
      ,[b2b]
  FROM [MyDatabase].[dbo].[amazon_sale]